#!/usr/bin/env bash
# `init` and `sshconfig`.
#
# init is the first command anybody runs, so its output is the onboarding: it
# leaves behind a config, a key, and a printed list of what the human still owes
# the tool. It never overwrites something that already exists, because the most
# common reason to re-run it is that a later step failed.

# ---------------------------------------------------------------- init

cmd_init() {
  case "${1:-}" in
    -h|--help) printf 'usage: agentfleet init\n\nWrites ~/.config/agentfleet/config, an ssh key, and ~/.ssh/%s.conf.\nSafe to re-run: nothing that already exists is touched.\n' "$AF_NAME"; return 0 ;;
  esac
  af_need ssh-keygen

  local cfg="$AF_CONFIG" tmpl="$AF_DIR/agentfleet.conf.example" fresh=0
  if [ -f "$cfg" ]; then
    af_log "config    $cfg (already there, left alone)"
  else
    fresh=1
    [ -f "$tmpl" ] || af_die "template missing: $tmpl (broken install)"
    mkdir -p "$(dirname "$cfg")"
    cp "$tmpl" "$cfg"
    chmod 600 "$cfg"
    af_log "config    $cfg (created)"
    # Re-read it: the rest of init works off AF_NAME, AF_KEY and AF_USER, and
    # those now come from the file rather than from the built-in defaults.
    af_load_config
  fi

  # ed25519: short, supported by every current cloud image, and fast enough that
  # provisioning ten machines does not stall on key exchange. No passphrase,
  # because every ssh in this tool runs with BatchMode=yes and would hang on the
  # prompt. If that trade is wrong for you, use an agent-backed key and point
  # AF_KEY at it instead.
  if [ -f "$AF_KEY" ]; then
    af_log "ssh key   $AF_KEY (already there, left alone)"
  else
    mkdir -p "$(dirname "$AF_KEY")"
    chmod 700 "$(dirname "$AF_KEY")" 2>/dev/null || true
    ssh-keygen -q -t ed25519 -N '' -C "$AF_NAME" -f "$AF_KEY" || af_die "ssh-keygen failed"
    af_log "ssh key   $AF_KEY (generated)"
  fi

  if [ "$fresh" = 1 ]; then
    # The config was copied from the template seconds ago, so AF_HOSTS still
    # holds the example's placeholder names. Writing ssh blocks for machines
    # the user never named prepends an Include into their ~/.ssh/config for
    # three fictional hosts, and `agentfleet ls` then reports a fleet of
    # unreachable machines on a brand-new install. Wait until they have named
    # their own; provision regenerates this anyway.
    af_log "ssh config not written yet - name your machines first, then: agentfleet sshconfig"
  # A subshell so a provider that cannot load yet (no cloud CLI installed, a
  # provider name still set to the example value) does not abort onboarding
  # before the instructions print. The files it writes land on disk regardless.
  elif ! ( af_provider_load && cmd_sshconfig ); then
    af_warn "could not write the ssh config yet - fix the config, then: agentfleet sshconfig"
  fi

  af_init_next_steps
}

af_init_next_steps() {
  cat <<EOF

Three things now:

  1. Edit $AF_CONFIG
     Pick AF_PROVIDER, name your machines in AF_HOSTS (or set up the cloud
     section), and set AF_USER + AF_AGENT. It is the fully commented example:
     those four lines are all that has to change to get started.

  2. Let the key in.
     provider=ssh    ssh-copy-id -i $AF_KEY.pub <user>@<machine>   (once per machine)
     cloud provider  agentfleet up <name>                          (installs it for you)

  3. agentfleet provision all && agentfleet ls

Optional, one line, opt in if you want it:
  echo 'source $HOME/.config/agentfleet/aliases.sh' >> ~/.zshrc
  That file is regenerated by \`agentfleet sshconfig\` and gives you one alias
  per machine that drops you straight into its agent session.
EOF
}

# ---------------------------------------------------------------- sshconfig

# The Host names the user already declared in ~/.ssh/config, one per line.
#
# Our Include is prepended and ssh keeps the FIRST value it finds for each
# keyword, so a block we write for a name that is already theirs silently wins:
# their `Host w1 -> prod-db.example.com, User deploy` becomes our `HostName w1,
# User $AF_USER`, and their `ssh w1` stops reaching the machine it always did.
# That is someone else's access to a machine that has nothing to do with this
# tool, so those names are detected and left alone rather than taken over.
#
# Only exact literal names count. A pattern block (`Host *`, `Host web-*`) is
# not a claim on one name - it is meant to apply to whatever matches, and
# beating it is precisely why the Include is prepended. Reads the top-level
# file only: following the user's own Include directives is a parser, and a
# wrong guess there would refuse a write that is perfectly safe.
af_sshconfig_declared() {
  local main="$HOME/.ssh/config"
  [ -f "$main" ] || return 0
  # `Host` must be followed by whitespace, or `HostName` lines match too.
  sed -n 's/^[[:space:]]*[Hh][Oo][Ss][Tt][[:space:]][[:space:]]*//p' "$main" \
    | tr -s '[:space:]' '\n' | grep -v '^$' | grep -v '[*?!]' || true
}

af_sshconfig_taken() {
  local want="$1" tok
  for tok in $2; do
    if [ "$tok" = "$want" ]; then return 0; fi
  done
  return 1
}

# Regenerate ~/.ssh/$AF_NAME.conf so plain `ssh <host>` works, and so does every
# tool that shells out to ssh without knowing about agentfleet.
#
# TAILNET FIRST. A cloud firewall pinned to your current public IP stops
# answering the moment you change networks, and every machine goes unreachable
# while staying perfectly healthy. The tailnet address does not care. The
# <host>-direct alias keeps the provider address available for the opposite
# case: when the tailnet itself is what broke.
cmd_sshconfig() {
  case "${1:-}" in
    -h|--help) printf 'usage: agentfleet sshconfig\n\nRegenerates %s and the shell aliases from the current host list.\n' "$AF_SSH_CONF"; return 0 ;;
  esac

  local conf="$AF_SSH_CONF" tmp="$AF_SSH_CONF.$$" host addr direct names="" n=0
  local declared clash=""
  mkdir -p "$HOME/.ssh"
  chmod 700 "$HOME/.ssh" 2>/dev/null || true
  declared="$(af_sshconfig_declared)"

  {
    printf '# Managed by agentfleet. Regenerate: agentfleet sshconfig\n'
    printf '# Edits here are lost. The source of truth is %s\n' "$AF_CONFIG"
    for host in $(provider_list 2>/dev/null || true); do
      addr="$(af_host_addr "$host" 2>/dev/null || true)"
      direct="$(provider_addr "$host" 2>/dev/null || true)"
      if [ -z "$addr" ] && [ -z "$direct" ]; then
        af_warn "no address for $host - not written to the ssh config"
        continue
      fi
      [ -n "$addr" ] || addr="$direct"
      # A name the user already declared is theirs. Skipping the whole block -
      # and keeping the name out of the trailing options block below - leaves
      # their HostName, User and Port in force, which is also what makes the
      # documented "point AF_HOSTS at an ssh alias you already have" path work
      # instead of overwriting the alias it depends on.
      if af_sshconfig_taken "$host" "$declared"; then
        clash="$clash $host"
      else
        printf 'Host %s\n  HostName %s\n' "$host" "$addr"
        names="$names $host"
        n=$((n + 1))
      fi
      if [ -n "$direct" ]; then
        if af_sshconfig_taken "$host-direct" "$declared"; then
          clash="$clash $host-direct"
        else
          printf 'Host %s-direct\n  HostName %s\n' "$host" "$direct"
          names="$names $host-direct"
        fi
      fi
    done
    # One trailing block instead of a name-glob: a glob only matches if your
    # machines happen to share a prefix, and silently stops applying User and
    # IdentityFile the day someone names a machine differently.
    if [ -n "$names" ]; then
      printf 'Host%s\n' "$names"
      printf '  User %s\n' "$AF_USER"
      printf '  IdentityFile %s\n' "$AF_KEY"
      printf '  IdentitiesOnly yes\n'
      printf '  StrictHostKeyChecking accept-new\n'
      printf '  ServerAliveInterval 30\n'
    fi
  } >"$tmp"
  mv "$tmp" "$conf"

  if [ -n "$clash" ]; then
    af_warn "kept your own $HOME/.ssh/config block(s) for:$clash"
    af_warn "  agentfleet's Include is prepended, so writing its own would have overridden yours."
    af_warn "  Rename them in AF_HOSTS ($AF_CONFIG) if those are not the machines you meant."
  fi

  af_sshconfig_include "$conf"
  af_write_aliases

  printf '[sshconfig] %s host(s) -> %s\n' "$n" "$conf"
}

af_sshconfig_include() {
  local conf="$1" main="$HOME/.ssh/config"
  if grep -q "$AF_NAME.conf" "$main" 2>/dev/null; then
    return 0
  fi
  # Prepend, never append: ssh keeps the FIRST value it finds for each keyword,
  # so an Include at the bottom loses to any wildcard Host block already in the
  # file. Back the original up first - this is someone's hand-written config.
  if [ -f "$main" ]; then
    cp "$main" "$main.agentfleet-backup"
    af_log "backed up $main -> $main.agentfleet-backup"
  fi
  {
    printf 'Include %s\n\n' "$conf"
    if [ -f "$main" ]; then cat "$main"; fi
  } >"$main.agentfleet-new"
  mv "$main.agentfleet-new" "$main"
  chmod 600 "$main"
}

# Aliases go in a file that is rewritten whole, not appended to a shell rc.
# Appending leaves an alias per machine behind forever, and numbering them by
# position means deleting one machine silently repoints every alias after it.
af_write_aliases() {
  local dir="$HOME/.config/agentfleet" f host
  mkdir -p "$dir"
  f="$dir/aliases.sh"
  {
    printf '# Managed by agentfleet. Regenerate: agentfleet sshconfig\n'
    printf '# Opt in with: source %s\n' "$f"
    for host in $(provider_list 2>/dev/null || true); do
      printf "alias %s='ssh -t %s \"tmux new -A -s %s -c %s\"'\n" \
        "$host" "$host" "$AF_SESSION" "$AF_WORKDIR"
    done
  } >"$f"
}
